/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UserInterface;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Degree;
import model.userProfiles.Student;
import utils.Manager;

/**
 *
 * @author ashishnevan
 */
public class DegreeAuditJPanel extends javax.swing.JPanel {

    Degree currentDegree;
    Student s;
    Manager m;
    
    /** Creates new form DegreeAuditJPanel */
    public DegreeAuditJPanel(Student s, Manager m) {
        initComponents();
        this.s = s;
        this.m = m;
        currentDegree = s.getSelectedDegree();
        System.out.println("Current Degree is: " + s.getSelectedDegree().getName());
        comboCurrentDegree.setSelectedItem(currentDegree.getName());
        comboCurrentDegree.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCurrentDegree = new javax.swing.JComboBox<>();
        comboSwitchDegree = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAssessSwitch = new javax.swing.JButton();
        btnConfirmSwitch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRelevantCoursesNumber = new javax.swing.JTextField();
        btnGraduate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        comboCurrentDegree.setBackground(new java.awt.Color(255, 255, 255));
        comboCurrentDegree.setForeground(new java.awt.Color(0, 0, 0));
        comboCurrentDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSIS", "MSCS", "MSDS" }));

        comboSwitchDegree.setBackground(new java.awt.Color(255, 255, 255));
        comboSwitchDegree.setForeground(new java.awt.Color(0, 0, 0));
        comboSwitchDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSIS", "MSCS", "MSDS" }));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Current Degree");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Switch Degree");

        btnAssessSwitch.setBackground(new java.awt.Color(255, 255, 255));
        btnAssessSwitch.setForeground(new java.awt.Color(0, 0, 0));
        btnAssessSwitch.setText("Assess Switch");
        btnAssessSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssessSwitchActionPerformed(evt);
            }
        });

        btnConfirmSwitch.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmSwitch.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmSwitch.setText("Confirm Switch");
        btnConfirmSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSwitchActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No. of relevant courses");

        txtRelevantCoursesNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtRelevantCoursesNumber.setForeground(new java.awt.Color(0, 0, 0));

        btnGraduate.setBackground(new java.awt.Color(255, 255, 255));
        btnGraduate.setForeground(new java.awt.Color(0, 0, 0));
        btnGraduate.setText("Graduate");
        btnGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboCurrentDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGraduate))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmSwitch)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboSwitchDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAssessSwitch)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtRelevantCoursesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCurrentDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboSwitchDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnAssessSwitch)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRelevantCoursesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduate))
                .addGap(63, 63, 63)
                .addComponent(btnConfirmSwitch)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAssessSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssessSwitchActionPerformed
        // TODO add your handling code here:
        String switchDegreeName = comboSwitchDegree.getSelectedItem().toString();
        Degree switchDegree = m.getDegreeOfferings().get(switchDegreeName);
        int relevantCoursesNumber = currentDegree.switchDegree(s, switchDegree, true);
        txtRelevantCoursesNumber.setText(String.valueOf(relevantCoursesNumber));
    }//GEN-LAST:event_btnAssessSwitchActionPerformed

    private void btnConfirmSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSwitchActionPerformed
        // TODO add your handling code here:
        String switchDegreeName = comboSwitchDegree.getSelectedItem().toString();
        System.out.println("switchDegree field is: "+switchDegreeName);
        Degree switchDegree = m.getDegreeOfferings().get(switchDegreeName);
        System.out.println("Switch Degree object.name is: " + switchDegree.getName());
        System.out.println(switchDegree.getCourseRequirement());
        int relevantCoursesNumber = currentDegree.switchDegree(s, switchDegree, false);
        JOptionPane.showMessageDialog(this, "Degree switched!");
    }//GEN-LAST:event_btnConfirmSwitchActionPerformed

    private void btnGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduateActionPerformed
        // TODO add your handling code here:
        if (s.getSelectedDegree().audit(s)) {
            JOptionPane.showMessageDialog(this, "Congratulations on Graduation!", "Graduated", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Program requires 8 completed courses to graduate!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGraduateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssessSwitch;
    private javax.swing.JButton btnConfirmSwitch;
    private javax.swing.JButton btnGraduate;
    private javax.swing.JComboBox<String> comboCurrentDegree;
    private javax.swing.JComboBox<String> comboSwitchDegree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtRelevantCoursesNumber;
    // End of variables declaration//GEN-END:variables

}
